#!/bin/bash
cp -i vimrc ~/.vimrc
cp -i bashrc ~/.bashrc
cp -i bash_local ~/.bash_local
cp -i bash_aliases ~/.bash_aliases
cp -i bash_functions ~/.bash_functions
cp -i tmux.conf ~/.tmux.conf
cp -i gitconfig ~/.gitconfig
cp -i gitignore ~/.gitignore
cp -i bundles ~/.bundles
cp -i tmuxline ~/.tmuxline
